# Generated by Django 4.2.6 on 2023-11-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('avatar', models.CharField(default='avatar1.jpg', max_length=255)),
                ('guessed_words', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
